"""Build an A/B arm: same tasks, different model, isolated clone.

    python3 setup_ab.py ~/Code/witches_bricks --model gemma4:26b --tasks 4

Creates
  <project>_ab_<tag>/          a clone of MAIN at the current commit, with the
                               last N completed tasks rewound — same task text,
                               same contract, same gates
  profiles/<tag>.toml          a single-model ladder for the challenger
  ~/ab-<tag>/baseline/         the incumbent's velocity + traces, FILTERED to
                               exactly those N tasks

Then:
  SOVEREIGN_PROFILE=<tag> ./supervisor.sh <project>_ab_<tag> --features-only
  python3 ab_compare.py --arm baseline=~/ab-<tag>/baseline \\
                        --arm <tag>=<project>_ab_<tag>/logs

WHY A CLONE AND NOT A FLAG

The only comparison worth anything is the same tasks against the same contract.
Switching the model on a live run compares different tasks and answers nothing;
rewinding the live run destroys work. A clone at the current commit gives both
arms identical inputs and leaves the real run untouched.

The band is the LAST N completed tasks, deliberately: nothing built after them
exists yet, so deleting their target files cannot break a later file that
imports them.

CLONE MAIN, NEVER HEAD

A live run sits on a `task-*` branch for most of its wall time, and a plain
`git clone` copies whichever branch HEAD points at. Doing that once produced an
arm cloned from a half-finished task: the run refused to start ("not on main"),
and had it started, the A/B would have been measured against a contaminated
tree. Cloning main is safe mid-run without stopping anything — main only moves
at a merge, so the snapshot is always a completed-task boundary.

READING THE RESULT

Attempts per task is the honest metric and it survives a concurrent run. Wall
time does not: two ollama models resident at once contend for RAM, and on a
32 GB machine that contention is what turned a 597s attempt into 5257s earlier
in this project. If both arms cannot be run separately, quote attempts and
escalations and treat the timings as noise.

Note also that tier 2+ numbers are survivorship-biased — those models only ever
see tasks that already failed. Compare TIER 1 attempts, or whole-task outcomes.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

PROFILE = """\
# A/B challenger arm: {model} as tier 1.
#
# Generated by setup_ab.py on {n} rewound task(s):
# {targets}
#
# Single-model ladder on purpose. Escalation to a different model would make the
# result unattributable — the point is to measure THIS model against the same
# tasks the incumbent already did.

[tiers.1]
model  = "{model}"
params = {params}
ctx    = {ctx}

[tiers.2]
model  = "{model}"
params = {params}
ctx    = {ctx}

[tiers.3]
model  = "{model}"
params = {params}
ctx    = {ctx}

[tiers.4]
model  = "{model}"
params = {params}
ctx    = {ctx}

[budget]
task_ceiling_s      = 3600
attempts_tier1      = 3
attempts_mid        = 2
attempts_last       = 2
foreign_park        = 2
quick_param_limit_b = {quick}

[run]
main_branch = "{main_branch}"
"""


def main_branch_of(project: str) -> str:
    """The project's integration branch, from .sovereign_config.json.

    Hardcoding "main" made this script unusable on any project that predates
    the rename — galaxican is on `master`, so `git clone --branch main` failed
    before a single task ran, and the generated profile would have handed
    work.py the wrong branch even if the clone had succeeded. NOTE: nothing else reads
    `main_branch` from this file — work.py and config.py resolve it from
    MAIN_BRANCH in the env, then a profile's [run] main_branch, then "main".
    This reads the project config so a generated profile carries the right
    branch; a non-A/B run still needs MAIN_BRANCH set in its .env.
    """
    cfg = os.path.join(project, ".sovereign_config.json")
    try:
        with open(cfg) as f:
            return json.load(f).get("main_branch") or "main"
    except Exception:
        return "main"


def sh(args, cwd=None, check=True):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if check and r.returncode != 0:
        print("FAILED:", " ".join(args))
        print(r.stdout + r.stderr)
        sys.exit(1)
    return r.stdout.strip()


def completed_tasks(roadmap_text):
    """(line_index, target_file) for every checked task, in roadmap order."""
    out = []
    for i, line in enumerate(roadmap_text.split("\n")):
        if not line.startswith("- [x]"):
            continue
        m = re.search(r"In (\S+?):", line)
        out.append((i, m.group(1) if m else None))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--model", required=True,
                    help="challenger model, exactly as `ollama list` shows it")
    ap.add_argument("--tasks", type=int, default=4,
                    help="how many of the last completed tasks to rewind")
    ap.add_argument("--params", type=float, default=26,
                    help="challenger parameter count in billions")
    ap.add_argument("--ctx", type=int, default=16384)
    ap.add_argument("--tag", default=None)
    ap.add_argument("--band", default=None,
                    help="comma-separated target files to rewind instead of the "
                         "last N — use when the last N were done by the wrong "
                         "model or are the wrong KIND of task")
    ap.add_argument("--keep-going", action="store_true",
                    help="do not truncate the roadmap after the band; the arm "
                         "will continue into every remaining task")
    args = ap.parse_args()

    project = os.path.abspath(os.path.expanduser(args.project))
    tag = args.tag or re.sub(r"[^a-z0-9]+", "", args.model.split(":")[-1].lower())
    clone = f"{project}_ab_{tag}"
    sovereign = os.path.dirname(os.path.abspath(__file__))
    baseline = os.path.expanduser(f"~/ab-{tag}/baseline")

    if "'" in clone:
        sys.exit("clone path contains an apostrophe; flutter test will not compile")
    if os.path.exists(clone):
        sys.exit(f"{clone} already exists — remove it or pass a different --tag")

    MAIN = main_branch_of(project)
    branch = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=project)
    head = sh(["git", "rev-parse", "--short", MAIN], cwd=project)
    if branch != MAIN:
        print(f"note: source is on '{branch}' — a run is live. Cloning {MAIN} "
              f"@ {head}, which is a completed-task boundary.")
    else:
        print(f"cloning {project} {MAIN} @ {head}")
    sh(["git", "clone", "--no-hardlinks", "--branch", MAIN, "--single-branch",
        project, clone])
    on = sh(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=clone)
    if on != MAIN:
        sys.exit(f"clone landed on '{on}', expected {MAIN}")

    rm_path = os.path.join(clone, "ROADMAP.md")
    text = open(rm_path).read()
    done = completed_tasks(text)
    # Only meaningful for the "last N" path — an explicit --band names its own
    # tasks and is validated against `done` below.
    if not args.band and len(done) < args.tasks:
        sys.exit(f"only {len(done)} completed tasks; cannot rewind {args.tasks}")

    if args.band:
        want = [b.strip() for b in args.band.split(",") if b.strip()]
        by_target = {t: i for i, t in done if t}
        missing = [w for w in want if not any(w in t for t in by_target)]
        if missing:
            sys.exit(f"--band entries not found among completed tasks: {missing}")
        band = [(by_target[t], t) for w in want for t in by_target if w in t]
    else:
        band = done[-args.tasks:]
    # REFUSE a band that later, still-present files import.
    #
    # Rewinding deletes the band's target files. Anything completed AFTER them
    # survives in the clone — and if it imports a deleted file, the validate
    # command fails on every attempt no matter what the challenger writes. That
    # is not a model result, it is a broken arm, and it looks identical to
    # incompetence in the summary: 0/4, twenty-one attempts, one error about a
    # missing URI.
    #
    # This is why the default band is the LAST N completed tasks. --band lets
    # you pick a middle band, so --band has to check what the default gets for
    # free. (2026-08-11: a gemma4:26b arm scored 0/4 purely because
    # legalActions.dart imported all four rewound rule modules.)
    band_files = {t for _, t in band if t}
    dependents = {}
    lib_root = os.path.join(clone, "lib")
    for dirpath, _d, files in os.walk(lib_root):
        for fn in files:
            if not fn.endswith(".dart"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, clone).replace("\\", "/")
            if rel in band_files:
                continue
            try:
                src = open(full, errors="ignore").read()
            except OSError:
                continue
            for bf in band_files:
                if os.path.basename(bf) in src and bf.split("lib/")[-1] in src:
                    dependents.setdefault(rel, []).append(bf)
    if dependents:
        print("\n✗ this band cannot be rewound — files that would REMAIN import it:")
        for dep, needs in sorted(dependents.items()):
            print(f"    {dep}")
            for n in needs:
                print(f"        imports {n}")
        print("\n  Every attempt would fail on a missing import, whatever the model "
              "writes.\n  Either add those files to --band too, or drop --band and use "
              "--tasks N,\n  which takes the last N completed tasks and cannot have "
              "this problem.")
        shutil.rmtree(clone, ignore_errors=True)
        sys.exit(1)

    lines = text.split("\n")
    targets = []
    for idx, target in band:
        lines[idx] = lines[idx].replace("- [x]", "- [ ]", 1)
        if target:
            targets.append(target)
            p = os.path.join(clone, target)
            if os.path.exists(p):
                os.remove(p)
    # Truncate everything after the band so the arm STOPS when the experiment
    # does. Without this the challenger rolls straight on into every remaining
    # task, and a "4-task A/B" quietly becomes an unattended full run on an
    # unproven model — you get your answer, then keep paying for it.
    if not args.keep_going:
        last = max(i for i, _ in band)
        dropped = 0
        for i in range(last + 1, len(lines)):
            if lines[i].startswith("- [ ]"):
                lines[i] = "<!-- ab-arm: out of band -- " + lines[i] + " -->"
                dropped += 1
        print(f"parked {dropped} later task(s) so the arm ends after the band")

    open(rm_path, "w").write("\n".join(lines))

    shutil.rmtree(os.path.join(clone, "logs"), ignore_errors=True)
    sh(["git", "add", "-A"], cwd=clone)
    # Pin the identity: a fresh clone does not inherit the source repo's local
    # config, so on a machine where identity is only set per-repo this commit
    # fails and leaves the arm half-built.
    sh(["git", "-c", "user.email=ab@sovereign.local", "-c", "user.name=sovereign-ab",
        "commit", "-m", f"A/B arm {tag}: rewind {len(targets)} tasks"], cwd=clone)

    os.makedirs(baseline, exist_ok=True)
    kept = {"velocity.jsonl": 0, "task_traces.jsonl": 0}
    for fn in kept:
        src = os.path.join(project, "logs", fn)
        if not os.path.exists(src):
            continue
        # Keep only the LAST record per target file.
        #
        # A task that failed, was reverted and re-run leaves several records,
        # and counting them all makes the incumbent look worse than it was:
        # a clean 4-for-4 was reported as "5/8 tasks done" with hard_ceiling
        # errors attributed to it, because two of the band files had earlier
        # aborted runs in the log. The last record is the one that landed.
        latest = {}
        for line in open(src):
            try:
                rec = json.loads(line)
            except Exception:
                continue
            for t in targets:
                if t and t in rec.get("task", ""):
                    latest[t] = line
                    break
        with open(os.path.join(baseline, fn), "w") as out:
            for t in targets:
                if t in latest:
                    out.write(latest[t])
                    kept[fn] += 1

    prof_dir = os.path.join(sovereign, "profiles")
    os.makedirs(prof_dir, exist_ok=True)
    prof_path = os.path.join(prof_dir, f"{tag}.toml")
    with open(prof_path, "w") as f:
        f.write(PROFILE.format(model=args.model, params=args.params, ctx=args.ctx,
                               quick=args.params + 1, n=len(targets),
                               main_branch=MAIN,
                               targets="\n# ".join(targets)))

    print(f"\nclone     {clone}")
    print(f"rewound   {len(targets)} task(s): {', '.join(targets)}")
    print(f"baseline  {baseline}  ({kept['velocity.jsonl']} velocity, "
          f"{kept['task_traces.jsonl']} trace records)")
    print(f"profile   {prof_path}")
    print("\nRun the challenger:")
    print(f"  cd {clone} && flutter pub get")
    print(f"  cd {sovereign}")
    print(f"  SOVEREIGN_PROFILE={tag} ./supervisor.sh {clone} --features-only")
    print("\nThen compare:")
    print(f"  cd {sovereign}")
    print(f"  python3 ab_compare.py --arm baseline={baseline} "
          f"--arm {tag}={clone}/logs")


if __name__ == "__main__":
    main()
