"""
dart_riverpod — Riverpod state management. Load only if the project uses it.

Generated by tools/split_hints.py from the original
monolithic hints.py (2026-07-25). Entries are verbatim.
"""

BAD_PATTERNS: list[tuple[str, str]] = [
    ('flutter_riverpod/flutter_river(?!pod\\.dart)',
     "IMPORT TYPO: The correct import is 'package:flutter_riverpod/flutter_riverpod.dart'. Do NOT use flutter_riverpad, flutter_riverpost, or any other variant."),
]

ERROR_HINTS: list[tuple[str, str]] = [
    ("StateNotifier.*not found|StateNotifierProvider.*not found|Type 'StateNotifier' not found|Method not found: 'StateNotifierProvider'",
     '⚠️  RIVERPOD 3.x: StateNotifier and StateNotifierProvider are REMOVED.\n  Migrate to Notifier<T> + NotifierProvider:\n  OLD (broken):\n    class MyNotifier extends StateNotifier<MyState> {\n      MyNotifier() : super(MyState.initial);\n      void doSomething() { state = newState; }\n    }\n    final myProvider = StateNotifierProvider<MyNotifier, MyState>((ref) => MyNotifier());\n  NEW (correct):\n    class MyNotifier extends Notifier<MyState> {\n      @override\n      MyState build() => MyState.initial;  // replaces super(initialState)\n      void doSomething() { state = newState; }  // state getter/setter unchanged\n    }\n    final myProvider = NotifierProvider<MyNotifier, MyState>(() => MyNotifier());\n  ref.read(myProvider.notifier) still works. ref.watch(myProvider) still works.\n  WidgetRef and Ref are SEPARATE types in Riverpod 3.x — do not pass WidgetRef as Ref.'),
    ('Classes can only extend other classes|extends.*Provider|extends.*Notifier(?!<)',
     "⚠️  A class is trying to extend a provider or non-class type. Riverpod providers are not classes you extend. Correct patterns:\n  class MyNotifier extends Notifier<MyState> { ... }  // Riverpod 3.x\n  final myProvider = NotifierProvider<MyNotifier, MyState>(() => MyNotifier());\nNever write 'extends fusionProvider' or 'extends NotifierProvider'."),
    ('Classes can only extend other classes.*capture|capture.*Classes can only extend',
     "⚠️  CaptureEventNotifier / CaptureMessageNotifier must extend StateNotifier<String>, not a provider.\n  CORRECT:\n    class CaptureMessageNotifier extends StateNotifier<String> {\n      CaptureMessageNotifier() : super('');\n    }\n  WRONG: extends captureMessageProvider, extends StateNotifierProvider, extends Provider.\n  Providers are instances created by the framework — you never extend them."),
    ("'expect' isn't defined|The function 'expect' isn't defined|'expect'.*isn't defined.*Try importing",
     "⚠️  MISSING TEST IMPORT: 'expect' is defined in package:flutter_test.\n  Every test file must start with these imports:\n    import 'package:flutter_test/flutter_test.dart';\n    import 'package:flutter_riverpod/flutter_riverpod.dart';  // if using ProviderContainer\n  Add them as the very first lines of the file, before any other imports.\n  Also ensure the test file has a void main() { } entry point wrapping all test() calls."),
    ("'ProviderContainer' isn't defined|The function 'ProviderContainer' isn't defined|ProviderContainer.*isn't defined.*Try importing",
     "⚠️  MISSING RIVERPOD TEST IMPORT: ProviderContainer is in flutter_riverpod.\n  Add to the top of the test file:\n    import 'package:flutter_riverpod/flutter_riverpod.dart';\n  Standard test boilerplate for Riverpod:\n    final container = ProviderContainer();\n    addTearDown(container.dispose);\n    final result = container.read(myProvider);\n  Never call ProviderContainer without first importing flutter_riverpod."),
    ("argument type 'ProviderContainer' can't be assigned to the parameter type 'Ref'|ProviderContainer.*can't be assigned.*Ref",
     '⚠️  PROVIDERCONTAINER IS NOT REF: ProviderContainer and Ref are different types.\n  ProviderContainer is test infrastructure — never pass it to production code.\n  WRONG (in test):\n    final container = ProviderContainer();\n    final system = PulsarFlareSystem(container);  // container is not a Ref\n  RIGHT — read the value directly from the container:\n    final container = ProviderContainer();\n    final notifier = container.read(myProvider.notifier);\n  Production code must accept Ref, not ProviderContainer, in constructors.'),
    ('final\\s+(?:Ref|WidgetRef)\\s+ref\\s*;.*GestureHandler|GestureHandler[^{]*final\\s+(?:Ref|WidgetRef)\\s+ref',
     "WRONG TYPE: GestureHandler.ref must be declared as 'final Ref ref' (Riverpod Ref, not WidgetRef).\n  GestureHandler is constructed inside a Provider, so it receives a plain Ref — not WidgetRef.\n  WRONG: final WidgetRef ref;\n  RIGHT: final Ref ref;\n  Import: import 'package:flutter_riverpod/flutter_riverpod.dart'; (Ref is in there)"),
]

