"""
dart_core — Dart language and analyzer traps. Applies to ANY Dart project.

Generated by tools/split_hints.py from the original
monolithic hints.py (2026-07-25). Entries are verbatim.
"""

BAD_PATTERNS: list[tuple[str, str]] = [
    ('\\bas\\?\\s+\\w',
     "SYNTAX ERROR: Dart does not have 'as?' optional casting (that's Swift/Kotlin). Use 'if (x is MyType)' or 'x is MyType ? x as MyType : null' instead."),
]

ERROR_HINTS: list[tuple[str, str]] = [
    ('missing_required_argument',
     '⚠️  A required constructor parameter is missing. Read the class definition carefully and provide ALL required: named parameters.'),
    ('undefined_method.*distanceTo|Offset.*distanceTo',
     '⚠️  Offset has no distanceTo(). Use (o - Offset(v.x, v.y)).distance instead.'),
    ('abstract_super_member_reference.*update|update.*abstract_super_member_reference',
     '⚠️  Game.update(double dt) is abstract — remove super.update(dt) from your override. Just call your own logic directly.'),
    ('const_with_non_const',
     "⚠️  const_with_non_const: a widget class has 'const' constructor but a non-const field initializer (e.g. 'final list = [SomeClass()]'). Fix: move the field into build() as a local variable, NOT an instance field."),
    ('uri_does_not_exist',
     "⚠️  uri_does_not_exist: a package import cannot be resolved. This means the package is missing from pubspec.yaml OR flutter pub get has not been run. Do NOT remove the import — the package is already in pubspec.yaml. This error will clear on its own once 'flutter pub get' is run. Rewrite the file with the same imports unchanged."),
    ('Directives must appear before any declarations|directive.*before.*declaration',
     "⚠️  IMPORT AFTER CLASS: All 'import' statements must appear at the TOP of the file,\n  before any class, enum, or function declarations.\n  Move every import to lines 1-N before the first 'class' or 'enum' keyword."),
    ("body might complete normally.*'null'.*return type.*'bool'|non_nullable_return_type",
     "⚠️  METHOD MISSING RETURN STATEMENT: A method declared to return 'bool' (or another non-nullable type) has no return statement — the body completes without returning a value. Add an explicit return:\n  static bool canAttack(...) {\n    if (someCondition) return false;\n    return true;  // ← must always return\n  }"),
    ("value of type 'double' can't be assigned to.*'int'|type 'double' is not a subtype of type 'int'",
     "⚠️  DOUBLE TO INT: A double value is being assigned to an int field.\n  Fix options:\n    1. Convert explicitly:  myInt = myDouble.toInt();\n    2. Round:               myInt = myDouble.round();\n    3. Change the field:    int myField → double myField\n  Common cause: arithmetic like 'width / 2' returns double even when both operands are int. Use integer division instead: 'width ~/ 2' returns int.\n  NEVER use 'as int' cast on a double — it will throw at runtime."),
    ("Target of URI doesn't exist.*_provider\\.dart|Target of URI doesn't exist.*_notifier\\.dart|Target of URI doesn't exist.*_service\\.dart",
     "⚠️  INVENTED IMPORT: You imported a file that does not exist in this project.\n  Before writing any import, verify the file is in the provided file list.\n  NEVER import a provider, notifier, or service file you just invented.\n  If you need something from a provider that doesn't exist yet:\n    Option A: Create that provider in the SAME response as the component.\n    Option B: Remove the import and hardcode a sensible default for now.\n  Writing an import to a non-existent file will always fail flutter analyze."),
    ("mixin_declares_constructor|Mixins can't declare constructors",
     '⚠️  MIXIN CONSTRUCTOR: Mixins cannot declare constructors — this is a Dart rule.\n  WRONG:\n    mixin CameraShakeMixin {\n      CameraShakeMixin(this.camera);  // ← illegal\n    }\n  RIGHT — use fields with late initialisation or an init() method instead:\n    mixin CameraShakeMixin {\n      late CameraComponent _camera;\n      void initShake(CameraComponent camera) { _camera = camera; }\n    }\n  Or convert to a regular class if you need a constructor:\n    class CameraShakeController {\n      CameraShakeController(this._camera);\n      final CameraComponent _camera;\n    }'),
    ("Fields can't be initialized in both the parameter list and the initializers|field_initialized_in_parameter_and_initializer",
     "⚠️  DOUBLE INITIALISATION: A field is set in both 'this.field' AND the initializer list.\n  WRONG: MyClass(this.health) : health = 10;\n  RIGHT — use one or the other:\n    MyClass(this.health);               // from parameter\n    MyClass(int h) : health = h;        // from initializer\n    MyClass({this.health = 10});        // named with default"),
    ("method 'Random' isn't defined|'Random' isn't defined for the type|The class 'Random' isn't defined",
     "⚠️  RANDOM MISSING IMPORT: Random is in dart:math — it is not auto-imported.\n  Add to the top of the file:\n    import 'dart:math';\n  Then use: final rng = Random(); final value = rng.nextInt(100);"),
    ("value of type '(\\w+)\\?' can't be assigned to.*'(\\w+)'[^?]|type '(\\w+)\\?' is not a subtype of type '(\\w+)'",
     '⚠️  NULL SAFETY: A nullable type (?) is being assigned to a non-nullable variable.\n  Fix options (choose the right one for context):\n    1. Null-check before use:   if (value != null) { useIt(value); }\n    2. Assert non-null:         useIt(value!);\n    3. Provide fallback:        useIt(value ?? defaultValue);\n    4. Make the target nullable: SomeType? myVar;\n  NEVER silence this with a cast — the null-safety system is correct.\n  Common pattern: firstWhere() returns T? — always handle the null case.'),
    ('enum_without_constants|The enum must have at least one constant',
     '⚠️  EMPTY ENUM: An enum was declared with no constants — this is a Dart error.\n  For AiStrategy, always define it with all variants:\n    enum AiStrategy { expander, builder, defender, aggressor }\n  Never declare an enum body with zero values:\n    enum AiStrategy {}  // ← invalid Dart\n  Define the enum BEFORE the class that uses it in the same file.'),
]

