"""
flutter_ui — Flutter widget/UI layer. Applies to any Flutter app.

Generated by tools/split_hints.py from the original
monolithic hints.py (2026-07-25). Entries are verbatim.
"""

BAD_PATTERNS: list[tuple[str, str]] = [
    ('\\.withOpacity\\(',
     'DEPRECATION ERROR: .withOpacity() is deprecated. Use .withValues(alpha: x) instead.'),
    ('Colors\\.magenta\\b',
     'COLOR ERROR: Colors.magenta does not exist in Flutter. Use Colors.purple (enemy faction color throughout this codebase).'),
    ('const\\s+\\w+\\(\\{[^}]*super\\.key[^}]*\\}\\)[\\s\\S]{0,400}final\\s+\\w+[^=]+=\\s*\\[',
     "CONST CONSTRUCTOR ERROR: A class with 'const MyWidget({super.key})' cannot have non-const field initializers (e.g. 'final list = [SomeClass()]'). Move the field initializer into the build() method as a local variable instead."),
]

ERROR_HINTS: list[tuple[str, str]] = [
    ('library_private_types_in_public_api',
     '⚠️  Private types (names starting with _) cannot appear in public class fields/methods. Either rename the private type to be public, or make the containing class private (_ClassName).'),
    ('deprecated_member_use.*withOpacity|withOpacity.*deprecated',
     '⚠️  .withOpacity() is deprecated — use .withValues(alpha: x) instead.'),
    ('annotate_overrides',
     "⚠️  annotate_overrides: a method/getter overrides a parent but is missing '@override'. Add @override on the line immediately before the method/getter declaration."),
]

